# Generated by Django 5.0.2 on 2024-02-07 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Social_Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(upload_to='social_icon/')),
                ('title', models.CharField(choices=[('Facebook', 'Facebook'), ('Twitter', 'Twitter'), ('Linkedin', 'Linkedin'), ('Instagram', 'Instagram'), ('Youtube', 'Youtube')], max_length=100)),
                ('url_link', models.URLField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
