# Generated by Django 5.0.2 on 2024-02-07 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_social_link'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Website_Config',
            new_name='Website_Logo',
        ),
    ]
