# Generated by Django 5.0.2 on 2024-02-07 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_website_config_website_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technology',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='technology/'),
        ),
        migrations.AlterField(
            model_name='technology_icon',
            name='icon',
            field=models.ImageField(upload_to='technology_icon/'),
        ),
    ]
